name: Release
on:
  release:
    types: [published]
jobs:
  push:
    name: Push release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install bazelisk
        run: curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.5.0/bazelisk-linux-amd64" | install -D /dev/stdin "${GITHUB_WORKSPACE}/bin/bazel"
      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: bazel run //cmd/adya:push_tag
        env:
          GIT_COMMIT: ${{ github.sha }}
          GIT_REF: ${{ github.event.release.tag_name }}
